# Generated by Django 5.1.2 on 2025-04-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_status', models.CharField(choices=[('reported', 'Reported'), ('not_reported', 'Not Reported'), ('deferred', 'Deferred'), ('on_leave', 'On Leave')], default='not_reported', max_length=20, verbose_name='Reporting Status')),
                ('reporting_date', models.DateField(blank=True, null=True, verbose_name='Reporting Date')),
                ('is_fees_cleared', models.BooleanField(default=False, verbose_name='Fees Cleared')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Administrative Notes')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reportings', to='students_portal.academicyear', verbose_name='Academic Year')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_records', to='students_portal.programme', verbose_name='Programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reportings', to='students_portal.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_records', to='students_portal.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Reporting',
                'verbose_name_plural': 'Student Reporting Records',
                'ordering': ['-academic_year__start_date', '-semester__number'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
