# Generated by Django 5.1.2 on 2025-04-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0002_studentreporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentunitgrade',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_grades', to='students_portal.gradesystem'),
        ),
        migrations.AlterField(
            model_name='studentunitgrade',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentunitgrade',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
