# Generated by Django 5.1.2 on 2025-04-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0004_studentcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Comment', 'verbose_name_plural': 'Student Comments'},
        ),
        migrations.AddField(
            model_name='studentcomment',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
