# Generated by Django 5.1.2 on 2025-04-06 23:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0006_announcement_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='lecture_notes/')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('unit_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_notes', to='students_portal.unitallocation')),
            ],
            options={
                'verbose_name_plural': 'Lecture Notes',
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
