# Generated by Django 5.1.2 on 2025-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0007_lecturenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('unit_allocation', 'week_number')},
        ),
    ]
