# Generated by Django 5.1.2 on 2025-04-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0008_attendancerecord_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='current_week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
