# Generated by Django 5.1.2 on 2025-04-07 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0009_semester_current_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=255, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_distance_km', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.lecturer')),
                ('unit_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.unitallocation')),
            ],
        ),
        migrations.CreateModel(
            name='QRAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('device_fingerprint', models.CharField(max_length=64)),
                ('scan_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('scan_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.qrattendancesession')),
            ],
            options={
                'unique_together': {('session', 'device_fingerprint'), ('session', 'student')},
            },
        ),
    ]
