# Generated by Django 5.1.2 on 2025-04-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0010_qrattendancesession_qrattendancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField()),
                ('building', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('start_time', 'end_time', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_portal.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_portal.semester')),
            ],
            options={
                'unique_together': {('semester', 'programme', 'year_of_study')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('custom', 'Custom Schedule')], default='weekly', max_length=20)),
                ('lecture_hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='students_portal.lecturehall')),
                ('unit_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_lessons', to='students_portal.unitallocation')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='students_portal.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_lessons', to='students_portal.timetable')),
            ],
            options={
                'unique_together': {('timetable', 'time_slot', 'lecture_hall')},
            },
        ),
    ]
