# Generated by Django 5.1.2 on 2025-04-16 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0011_lecturehall_timeslot_timetable_scheduledlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('supplementary', 'Supplementary Exam'), ('special', 'Special Exam')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Complete'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_code', models.CharField(max_length=12, unique=True)),
                ('code_expiry', models.DateTimeField()),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_applications', to='students_portal.student')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='AppliedExamUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('original_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.studentenrollment')),
                ('original_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.studentunitgrade')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.unit')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_units', to='students_portal.specialexamapplication')),
            ],
            options={
                'unique_together': {('application', 'unit')},
            },
        ),
    ]
