# Generated by Django 5.1.2 on 2025-04-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0013_hostel_room_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_allocated', models.DateField(auto_now_add=True)),
                ('date_vacated', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.academicyear')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.bed')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.hostel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_portal.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students_portal.student')),
            ],
            options={
                'unique_together': {('bed', 'academic_year'), ('student', 'academic_year')},
            },
        ),
    ]
