# Generated by Django 5.1.2 on 2025-04-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0014_hostelallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='date_vacated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
