# Generated by Django 5.1.2 on 2025-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0015_alter_hostelallocation_date_vacated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='date_vacated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
