# Generated by Django 5.1.2 on 2025-04-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0020_clubevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
