# Generated by Django 5.1.2 on 2025-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0021_semester_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
