# Generated by Django 5.2 on 2025-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0022_feesstructure_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='carried_forward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='is_carry_forward',
            field=models.BooleanField(default=False, help_text='Indicates if this record was created from a carry forward'),
        ),
    ]
